### ISSUE TITLE
Keylogger 

### ISSUE THREAD

**Issue by BrunoCliff** [Wielkimati/GBFR-Slimepede-Farm#2]
Bro why is this being flagged as keylogger ?

**Comment by Wielkimati** [comment]
False positive, which is common for autohotkey scripts. This IS is a scripts that's pressing buttons for user after he presses F1.
![image](https://github.com/Wielkimati/GBFR-Slimepede-Farm/assets/44122671/792035c8-859e-4407-a23c-e7be6ef50d9f)
I see some AVs are detecting this as a trojan, while most don't. This is to be expected with this kind of stuff.

If you're worried, compile the script yourself instead of creating pointless issues.
